# action.yml
name: 'AAP Automation Controller Action'
branding:
  icon: 'arrow-right-circle'
  color: 'red'
description: 'Launch Job Templates or Workflow Template and retrieve information from job output'
inputs:
  controller_host:
    description: "Automation controller URL."
    required: true
  controller_project:
    description: "Automation controller project."
    required: false
  controller_username:
    description: "Automation controller username."
    required: false
  controller_password:
    description: "Automation controller password."
    required: false
  validate_certs:
    required: false
    default: "true"
  job_template:
    description: "Name or ID of project, job_template or workflow_job_template."
    required: true
  extra_vars:
    description: "Pass extra command line variables to the playbook."
    required: false
runs:
  using: docker
  image: Dockerfile
  env:
    CONTROLLER_HOST: ${{ inputs.controller_host }}
    CONTROLLER_USERNAME: ${{ inputs.controller_username }}
    CONTROLLER_PASSWORD: ${{ inputs.controller_password }}
    CONTROLLER_VERIFY_SSL: ${{ inputs.validate_certs }}
    CONTROLLER_PROJECT: ${{ inputs.controller_project }}
    JOB_TEMPLATE: ${{ inputs.job_template }}
    EXTRA_VARS: ${{ inputs.extra_vars }}
